name: Assign issues to project
npm install @octokit/rest

on:
  issues:
    types: [labeled]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '16.x'

    - name: Install octokit
      run: npm install @octokit/rest
      
    - name: Install dependencies
      run: npm install

    - name: Assign to project
      id: assign
      uses: actions/github-script@v3
      with:
        script: |
          const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          if (context.payload.label.name === "bug") {
            const columnName = 'Todo';
            require('./add-issue-to-column')(columnName, context.payload.issue.number, octokit);
          }
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}