name: Assign issues to project

on:
  issues:
    types: [labeled]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '16.x'

    - name: Run npm init
      run: npm init --yes

    - name: Install dependencies
      run: |
        npm install @octokit/rest
        npm install add-issue-to-column
    
    - name: Assign to project
      id: assign
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        const { context } = require("@actions/github");
        const octokit = new require("@octokit/rest")({
          auth: `token ${process.env.MY_GITHUB_TOKEN}`
        });
        if (context.payload.label.name === "bug") {
          const columnName = 'Todo';
          require('./add-issue-to-column')(columnName, context.payload.issue.number, octokit);
        }