name: Assign issues to project

on:
  issues:
    types: [labeled]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Assign to project
      id: assign
      uses: actions/github-script@v3
      with:
        script: |
          const { context, GitHub } = require("@actions/github");
          const octokit = new GitHub(process.env.GITHUB_TOKEN);
          if (context.payload.label.name === "bug") {
            const columnName = 'Todo';
            require('./add-issue-to-column')(columnName, context.payload.issue.number, process.env.GITHUB_TOKEN);
          }
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}