name: Attribuer des issues à un projet

on:
  issues:
    types: [labeled]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm ci

    - name: Attribuer au projet
      id: assign
      uses: actions/github-script@v3
      with:
        script: |
          const context = require("@actions/github");
          const octokit = new require("@actions/github").GitHub(process.env.GITHUB_TOKEN);
          if (context.payload.label.name === "bug") {
            octokit.projects.createCard({
              column_id: 1,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
          }
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
