name: Assign issues to project

on:
  issues:
    types: [labeled]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install @actions/toolkit

    - name: Assign to project
      id: assign
      run: |
          const { Toolkit } = require('@actions/toolkit');
          const toolkit = new Toolkit();
          if (toolkit.context.payload.label.name === "bug") {
            const columnName = 'Todo';
            require('./add-issue-to-column')(columnName, toolkit.context.payload.issue.number, toolkit);
          }
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}