on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        MY_GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
        project-url: "https://github.com/Hildirial/projects/2"
        column-name: "Todo"
        label-name: "bug"
        columns-to-ignore: "In Review,Ready to deploy,Done"
