nname: Label Issue

on:
  issues:
    types: [labeled]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
    - name: check label
      if: github.event.action == 'labeled' && github.event.label.name == 'bug'
    - name: Run label_issue.py
      run: |
        python label_issue.py