name: Label Issue
on:
  issues:
    types: [labeled]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
    - name: check label
      if: github.event.action == 'labeled' && github.event.label.name == 'bug'
    - name: Move Issue
      run: |
        npx @peter-evans/move-project-card --column-name "To Do" --project-name "Bugs"