name: Create Bugs Issue

on:
  issues:
    types: [labeled]

jobs:
  create-bugs-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check if labeled "bug"
      if: github.event.label.name == 'bug'
      run: |
        echo "Issue labeled as bug. Creating Bugs issue..."

    - name: Create Bugs Issue
      uses: actions/create-an-issue@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        title: "Bug: ${{ github.event.issue.title }}"
        body: "Issue #${GITHUB_EVENT_NUMBER} has been labeled as a bug. Please add to Bugs."
        labels: "Bugs"
