name: Create Bugs Issue

on:
  issues:
    types: [labeled]

jobs:
  create-bugs-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install @actions/core @actions/github
    - name: Check if labeled "bug"
      if: github.event.label.name == 'bug'
      run: |
        echo "Issue labeled as bug. Creating Bugs issue..."
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Bugs Issue
      uses: ./.github/actions/create-bugs-issue
      with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
