name: Create Bugs Issue

on:
  issues:
    types: [labeled]

jobs:
  create-bugs-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      
    - name: Initialize npm
      run: npm init -y
      
    - name: Generate package-lock.json
      run: npm shrinkwrap
      
    - name: Install dependencies
      run: npm ci

    - name: Set Node.js 16.x
      uses: actions/setup-node@v2
      with:
          node-version: 16.x

    - name: Install actions/core
      run: npm install @actions/core
      
    - name: Install octokit/rest
      run: npm install @octokit/rest

    - name: Check if labeled "bug"
      if: github.event.label.name == 'bug'
      run: |
        echo "Issue labeled as bug. Creating Bugs issue..."

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Bugs Issue
      uses: ./.github/actions/create-bugs-issue
      with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
