name: Create Bugs Issue

on:
  issues:
    types: [labeled]

jobs:
  create-bugs-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check if labeled "bug"
      if: github.event.label.name == 'bug'
      run: |
        echo "Issue labeled as bug. Creating Bugs issue..."

    - name: Create Bugs Issue
      uses: ./.github/actions/create-bugs-issue
      with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
